version: '3.8'

services:

  api:
    image: manutencao_api
    networks:
      - manutencao
    ports:
      - "3000:3000"
    deploy:
      replicas: 1

  app:
    image: manutencao_app
    networks:
      - manutencao
    ports:
      - "3006:3006"
    deploy:
      replicas: 1

networks:
  manutencao:
    external: true

