# Use root/example as user/password credentials
version: '3.1'

services:

  support:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: support
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /etc/mysql/conf.d:/etc/mysql/conf.d
