version: '3.8'

services:
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    ports:
      - '8086:80'
      - '4436:443'
      - '81:81'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - npm_public
volumes:
  npm_data:
    external: true
  npm_letsencrypt:
    external: true

networks:
  npm_public:
    external: true
